language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
    - "createdb plants"
    - "python model.py"
    - "python server.py &"

# command to run tests
script: nosetests
