language: python
python:
  - "2.7"
before_install: "mv _secret.py secret.py"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
    - "createdb plants"
    - "python model.py"
# command to run tests
script: nosetests