language: python
python:
- 3.6.5
install: pip install -r requirements.txt
before_script:
- createdb plants
- python model.py
- python server.py &
script: nosetests
env:
  matrix:
  - secure: j56whUnw36jktxDSXAGYD9I5Z3ef99Nm2Sjo48n6mMvrMADJtwzihCZzivpqbX2FzB8snrgSshvTfIhfvGUCJ/OwLoJlJkkUGoZ33kxD5vw7tzEI1DW7BKHt8tutVP9UwL7p3s7iO4JbLFHeZm8yWySoINviEeuPZep0h5UHWydCSZIdIDp7H33rCi7urCUiQ679CIPmCugyuJJaLPYXbVl7b4p+g4+wt8S2O1JKTRhsH1mgKGaX6Q525r+Oih1kcv7NEm/ibNHbe7UufGANKtLHgOsAv5nt2Quzt2NpH23a7qnvrJoiZ/Yt/L8usj1neUFzTN3+4R5UQEVq7iwPNOIBb6kaWOBTx/+2KqR4nGQWgJRskxntsNynIYBnZlHPlmv/ieKBKwfama+r2dbxXVzd0msUpEU2rhWLotygWSrE0TjnbicT6FlXglmG9ZO3kjoHtIvyQ8eA/KXr+GVab/EXG6XED+Aq+fNqe3EFIH6B4BEz5YZVB9WUHtHW1zMiS5y1+YpZbrKY9i2clhA584i7fzpP1xGgvS7Wz+LMGAnWTz8kkeFgS9kPtL2O9fh/Y4W8HOIW+YuDPObNY8pc/3IR+TL0w9+soVNiOEnqQVdF9T1BBg/lr8Mk0jMXX+Y4oQm6O+WOMk24Wn8EgBkCWkj+fad4OyYwm7byrhDfcVQ=
  - secure: G9v6L6vSL4tGxGYy4TMJcqGhIGeO0eIz4DJefbqWTYiL2YyY+8/BDJnsBX/XIb1w9hpHP7ssURBtclxpIcForZJQQ03RmmtYD+hETJus65Wc43UmXLKGxbHo2qusmXdc9OjAXuPz4qDOvpBw/U8T/buMDOa1ses6n58g6uj+fGoBzd29dGA8qip95TQPqj24OOz8D9HmeIWTRvndO88MC7b4HWzBvhvgWpk7iwq/KrE/uKLPL6kLj4gvzBNbwEyMpn4LtNtITYCW2mA8uWG5b4dkPs5Zhj1kBvgIeCa7O0+f0fYuuoY1eMKDN6FuhhoavlE5bKt2LBgrYl0QEOHCgaUVOJUAJMkFLNKYMd8ZAUEtN2wu6HlX0O7tGb0Hy2RLfRKKGU5ynj6MokuG1tsYDl4hslxZ4LGwmw7TG5VoNQAeHkDySfrPHg88/vDT8o4sZygc99KaNSaqxwzlxXeduQCb/C+ZVrDu45BMJ0quBnkUXe58yWfmNWerjEKJDVR2GpdrMcHXvWzpxDZbp0T6OthZ4GZCUk5vghPz/zLAx0OQWsq9CKWkn8UOM1WxGFqDI6GY0b1VW+e3gPfdy4qDoV1Nx/7Ks311Sev7ClTEY5uKQ2jmQQ+NDM3nwMET3Nl0OjW/eAmoLh1zdvH+FYH7B9M79kdqkjQaC3+z7dAGnZE=
